apiVersion: v1
kind: Secret
metadata:
  name: hash-salts
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
type: Opaque
data:
{{ ( include "secret.hashsalts" . ) | indent 2 -}}
