apiVersion: v1
kind: Secret
metadata:
  name: ctrl-postgres
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/resource-policy": keep
type: Opaque
data:
{{ ( include "secret.postgres" . ) | indent 2 -}}