services:

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:8025']
      interval: 2s
      timeout: 2s
      retries: 10

  backend:
    image: ${BACKEND_IMAGE_URL}
    depends_on:
      db-test:
        condition: service_healthy
      mailhog:
        condition: service_healthy
    env_file:
      - ./application/backend/.env.dockere2e
    environment:
      - NODE_ENV=e2e
      - CONFIG_DIR=/app/config
    volumes:
      - ./application/common/config.e2e.json5:/app/config/config.json5
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5000/
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - '5000:5000'

  db-test:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    env_file:
      - ./application/backend/.env.dockere2e
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -p 5432']
      interval: 1s
      timeout: 1s
      retries: 60
    command: ['postgres', '-c', 'log_statement=all', '-p', '5432']

  user-client:
    image: ${USER_CLIENT_IMAGE_URL}
    ports:
      - '5002:80'
    env_file:
      - ./application/backend/.env.dockere2e
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80']
      interval: 2s
      timeout: 2s
      retries: 10

  admin-client:
    image: ${ADMIN_CLIENT_IMAGE_URL}
    ports:
      - '5003:80'
    env_file:
      - ./application/backend/.env.dockere2e
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80']
      interval: 2s
      timeout: 2s
      retries: 10
