services:
  db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    env_file:
      - ./application/backend/.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 1s
      retries: 60
    command: ['postgres', '-c', 'log_statement=all']
    volumes:
      - ctrl-db:/var/lib/postgresql/data

  db-test:
    image: postgres:16-alpine
    ports:
      - '5433:5433'
    env_file:
      - ./application/backend/.env.test
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -p 5433']
      interval: 1s
      timeout: 1s
      retries: 60
    command: ['postgres', '-c', 'log_statement=all', '-p', '5433']

  backend-test:
    depends_on:
      db-test:
        condition: service_healthy
        restart: true
    build:
      dockerfile: ./application/backend/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    env_file:
      - ./application/backend/.env.dockertest
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5001/
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - '5001:5001'

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  ctrl-db:
