services:
  db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    env_file:
      - ./application/backend/.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 1s
      retries: 60
    command: ['postgres', '-c', 'log_statement=all']
    volumes:
      - ctrl-db:/var/lib/postgresql/data

  db-test:
    image: postgres:16-alpine
    ports:
      - '5433:5433'
    env_file:
      - ./application/backend/.env.test
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -p 5433']
      interval: 1s
      timeout: 1s
      retries: 60
    command: ['postgres', '-c', 'log_statement=all', '-p', '5433']

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:8025']
      interval: 2s
      timeout: 2s
      retries: 10

  backend-test:
    depends_on:
      db-test:
        condition: service_healthy
        restart: true
      mailhog:
        condition: service_healthy
    build:
      dockerfile: ./application/backend/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    env_file:
      - ./application/backend/.env.dockertest
    environment:
      - NODE_ENV=${E2E_NODE_ENV:-test}
    volumes:
      - ./application/common/e2e-tests/config.e2e.json5:/app/config/config.json5
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5001/
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - '5001:5001'

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  ctrl-db:
