import cors from 'cors'
import { backendPort } from '../../common/src/index'
import express, { Request, type Application, Response } from 'express'
import { type Server } from 'http'
import swaggerUi from 'swagger-ui-express'
import { RegisterRoutes } from './routes' // This is a file generated by TSOA

export class Api {
  public app: Application
  private server?: Server
  public port: number = backendPort

  constructor() {
    // App config
    this.app = express()
    this.app.use(express.json())
    this.app.use(cors())

    // Set up Swagger UI to serve the API documentation
    this.app.use('/docs', swaggerUi.serve, async (req: Request, res: Response) => {
      return res.send(swaggerUi.generateHTML(await import('../swagger.json')))
    })

    // Register TSOA generated routes
    RegisterRoutes(this.app)
  }

  run(): void {
    this.server = this.app.listen(this.port, () => {})
    console.log(`Listening on http://localhost:${backendPort}`)
    console.log(`Documentation at http://localhost:${backendPort}/docs`)
  }

  stop(): void {
    if (this.server != null) {
      this.server.close()
    }
  }
}
