import cors from 'cors'
import express, { Response, Request, Application } from 'express'
import { type Server } from 'http'
import swaggerUi from 'swagger-ui-express'
import { RegisterRoutes } from './routes' // This is a file generated by TSOA
import { backendPort } from 'common/src/config'
import logger from 'common/src/logger'
import { ErrorHandler } from './middlewares/ErrorHandler'

export class Api {
  public app: Application
  private server?: Server
  public port: number = backendPort

  constructor() {
    // App config
    this.app = express()
    this.app.use(express.json())
    this.app.use(cors())

    // Set up Swagger UI to serve the API documentation
    this.app.use('/docs', swaggerUi.serve, async (req: Request, res: Response) => {
      return res.send(swaggerUi.generateHTML(await import('../swagger.json')))
    })

    // Register TSOA generated routes
    RegisterRoutes(this.app)

    // Error handling middleware
    this.app.use(ErrorHandler)
  }

  run(): void {
    this.server = this.app.listen(this.port, () => {})
    logger.info(`Listening on http://localhost:${backendPort} `)
    logger.info(`Documentation at http://localhost:${backendPort}/docs `)
  }

  stop(): void {
    if (this.server != null) {
      this.server.close()
    }
  }
}
