import cors from 'cors'
import express, { Response, Request, Application, ErrorRequestHandler, Router } from 'express'
import { type Server } from 'http'
import swaggerUi from 'swagger-ui-express'
import { RegisterRoutes } from './routes' // This is a file generated by TSOA
import logger from 'common/src/logger'
import { ErrorHandler } from './middlewares/ErrorHandler'
import config from 'config'

export class Api {
  public app: Application
  private server?: Server
  public port: number = (process.env.PORT && Number(process.env.PORT)) || 5000

  constructor() {
    //Load OIDC Config
    if (config) {
      logger.info('Loaded config')
    }
    // App config
    this.app = express()
    this.app.use(express.json())
    this.app.use(cors())

    // Set up Swagger UI to serve the API documentation
    this.app.use('/docs', ...swaggerUi.serve, async (req: Request, res: Response) => {
      res.send(swaggerUi.generateHTML(await import('../swagger.json')))
    })

    // Register TSOA generated routes on a router
    const apiRouter = Router()
    RegisterRoutes(apiRouter)

    // Mount the router at both / and /api
    this.app.use('/', apiRouter)
    this.app.use('/api', apiRouter)

    // Error handling middleware
    this.app.use(ErrorHandler as ErrorRequestHandler)
  }

  run(): void {
    this.server = this.app.listen(this.port, () => {})
    logger.info(`Listening on http://localhost:${this.port} `)
    logger.info(`Documentation at http://localhost:${this.port}/docs `)
  }

  stop(): void {
    if (this.server != null) {
      this.server.close()
    }
  }
}
