{{- if .Values.demoMode.enabled }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-reset
spec:
  timeZone: "Australia/Sydney"
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-backend
            image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.Version }}"
            imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
            env:
              - name: POSTGRES_HOST
                value: ctrl-postgresql
              - name: HOSTNAME
              {{ with .Values.ingress.hosts.userClient }}
                value: {{ .hostname | quote }}
              {{ end }}
              - name: EXAMPLE_ADMIN_EMAIL
                value: admin@example.com
              - name: EXAMPLE_ADMIN_PASSWORD
                value: Testpassword1
              - name: EXAMPLE_PARTICIPANT_EMAIL
                value: user@example.com
              - name: EXAMPLE_PARTICIPANT_PASSWORD
                value: Testpassword2
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: ctrl-postgresql
                    key: postgres-password
            command:
            - /bin/sh
            - -c
            - date; yarn prisma:wipe && yarn prisma:seed
          restartPolicy: OnFailure

{{- end }}
