apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    {{- include "ctrl.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: BACKEND
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ctrl.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: BACKEND
    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ctrl.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            - name: POSTGRES_HOST
              value: ctrl-postgres
            - name: HOSTNAME
            {{ with .Values.ingress.hosts.userClient }}
              value: {{ .hostname | quote }}
            {{ end }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ctrl-postgres
                  key: postgres-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: jwt
            - name: PRISMA_FIELD_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: aeskey
                  key: aeskey
            - name: CONFIG_DIR
              value: '/config'
            
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          startupProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
          - name: config
            mountPath: "/config"
            readOnly: false
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      
      volumes:
      - name: config
        configMap:
          name: ctrl-config
          items:
          - key: "valuesconfig.json5"
            path: "values.json5"
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
