apiVersion: v2
name: ctrl
description: A Helm chart for Kubernetes

type: application

dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.3.0
version: 1.0.0
