apiVersion: v2
name: ctrl
description: A Helm chart for Kubernetes

type: application

dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.3.0
  - name: reloader
    repository: https://stakater.github.io/stakater-charts
    version: 2.1.4

version: 1.2.2
