name: Build and Push

on:
  workflow_run:
    workflows: ["Build checks"]
    branches: ["dev", "rel*"]
    types: [completed]

jobs:
  build_push:
    name: Build and Push ${{ matrix.name }}
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      image_tag: ${{ steps.branch_sha.outputs.sha }}
    permissions:
      contents: "read"
      id-token: "write"
    strategy:
      matrix:
        name: [backend, user-client, admin-client]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Get latest branch SHA
        id: branch_sha
        run: |
          git fetch origin ${{ github.event.workflow_run.head_branch }}
          echo "sha=$(git rev-parse origin/${{ github.event.workflow_run.head_branch }})" >> $GITHUB_OUTPUT

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/43338454952/locations/global/workloadIdentityPools/ctrl-id-pool/providers/github-provider"
          service_account: "ctrl-ci-sa@ctrl-358804.iam.gserviceaccount.com"

      - name: Docker auth
        run: gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Parse node version
        id: nvm
        uses: ./.github/actions/parse-node-version

      - name: Check node version
        run: echo "node_version=${{ steps.nvm.outputs.node_version }}"

      - name: Get Chart version
        id: chart_version
        run: |
          version=$(grep '^version:' .helm/ctrl/Chart.yaml | awk '{print $2}')
          echo "chart_version=$version" >> $GITHUB_OUTPUT

      - name: Get short SHA
        id: short_sha
        run: echo "short_sha=$(echo ${{ steps.branch_sha.outputs.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build and Push ${{ matrix.name }} Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: application/${{ matrix.name }}/Dockerfile
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: |
            australia-southeast1-docker.pkg.dev/dsp-registry-410602/garvan-public/ctrl-${{ matrix.name }}:${{ github.event.workflow_run.head_branch == 'main' && 'latest' || 'dev' }}
            australia-southeast1-docker.pkg.dev/dsp-registry-410602/garvan-public/ctrl-${{ matrix.name }}:${{ steps.branch_sha.outputs.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_VERSION=${{ steps.nvm.outputs.node_version }}
            APP_VERSION=${{ steps.chart_version.outputs.chart_version }}_${{ steps.short_sha.outputs.short_sha }}

  e2e-tests:
    needs: build_push
    name: E2E Tests
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/43338454952/locations/global/workloadIdentityPools/ctrl-id-pool/providers/github-provider"
          service_account: "ctrl-ci-sa@ctrl-358804.iam.gserviceaccount.com"

      - name: Docker auth
        run: gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - name: Enable Corepack
        run: corepack enable

      - name: Configure Environment
        run: cp ./application/backend/.env.test ./application/backend/.env

      - name: Parse node version
        id: nvm
        uses: ./.github/actions/parse-node-version

      - name: Setup Nodejs and npm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.node_version }}
          cache: "yarn"

      - run: yarn install

      - name: Pull and Start Services
        run: |
          export IMAGE_TAG=${{ needs.build_push.outputs.image_tag }}
          docker compose -f docker-compose.e2e.yml up -d --wait

      - name: Run E2E Tests
        run: |
          yarn workspace backend prisma:generate
          npx dotenv -e ./application/backend/.env.test -- npx cypress run --project application/common/e2e-tests

      - name: Tear Down Services
        if: always()
        run: |
          export IMAGE_TAG=${{ needs.build_push.outputs.image_tag }}
          docker compose -f docker-compose.e2e.yml down

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: application/common/e2e-tests/cypress/screenshots

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: application/common/e2e-tests/cypress/videos

  push_helm_charts:
    name: Push Helm Charts
    runs-on: ubuntu-latest
    needs: build_push
    if: ${{ github.event.workflow_run.head_branch == 'dev' }} # Only push updated helm charts if on dev branch
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/43338454952/locations/global/workloadIdentityPools/ctrl-id-pool/providers/github-provider"
          service_account: "ctrl-ci-sa@ctrl-358804.iam.gserviceaccount.com"

      - name: Set up Google Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: ctrl-358804

      - name: Copy Helm charts to VM
        run: |
          gcloud --quiet beta compute ssh ctrl-dev \
            --zone=australia-southeast1-a \
            --project=ctrl-358804 \
            --command="mkdir -p /opt/ctrl/chart && rm -rf /opt/ctrl/chart/{*,.*} 2>/dev/null || true" && \
          gcloud --quiet beta compute scp --recurse .helm/ctrl/ \
            ctrl-dev:/opt/ctrl/chart/ \
            --zone=australia-southeast1-a \
            --project=ctrl-358804

  restart-dev-deployments:
    name: Restart Dev Deployments
    needs: push_helm_charts
    if: ${{ github.event.workflow_run.head_branch == 'dev' }} # Only restart if on dev branch
    uses: Garvan-Data-Science-Platform/ctrl/.github/workflows/restart-deployments.yml@main
    secrets: inherit
    with:
      environment: dev
