name: Build and push

on:
  workflow_run:
    workflows: ['Build checks']
    branches: [main]
    types: [completed]

jobs:
  release:
    name: build and push ${{ matrix.name }}
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        name: [backend, user-client, admin-client]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/43338454952/locations/global/workloadIdentityPools/ctrl-next-id-pool/providers/github-provider'
          service_account: 'ctrl-ci-sa@ctrl-358804.iam.gserviceaccount.com'

      - name: 'Docker auth'
        run: gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: application/${{ matrix.name }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            australia-southeast1-docker.pkg.dev/dsp-registry-410602/garvan-public/ctrl-${{ matrix.name }}:latest
            australia-southeast1-docker.pkg.dev/dsp-registry-410602/garvan-public/ctrl-${{ matrix.name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
