name: Build checks

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: build and check
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Configure Environment
        run: cp ./application/backend/.env.test ./application/backend/.env
      - name: Parse node version
        id: nvm
        uses: ./.github/actions/parse-node-version
      - name: Check node version
        run: echo "node_version=${{ steps.nvm.outputs.node_version }}"
      - name: Setup Nodejs and npm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.node_version }}
          cache: 'yarn'
      - run: yarn install && yarn prisma:generate
      - name: Check Types
        run: yarn type-check
      - name: Format Code
        run: yarn format
      - name: Lint Code
        run: yarn lint
      - run: make db && cp ./application/backend/.env.example ./application/backend/.env && yarn prisma:migrate && yarn prisma:seed

  test:
    needs: build
    name: test (${{ matrix.workspace }})
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        workspace: [backend, admin-client, common, user-client, integrations]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Configure Environment
        run: cp ./application/backend/.env.test ./application/backend/.env
      - name: Parse node version
        id: nvm
        uses: ./.github/actions/parse-node-version
      - name: Check node version
        run: echo "node_version=${{ steps.nvm.outputs.node_version }}"
      - name: Setup Nodejs and npm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.node_version }}
          cache: 'yarn'
      - run: yarn install
      - name: Run Tests
        env:
          MAILER_USERNAME: ${{ secrets.TEST_MAILER_USERNAME }}
          MAILER_PASSWORD: ${{ secrets.TEST_MAILER_PASSWORD }}
          CYPRESS_REDCAP_API_TOKEN: ${{ secrets.REDCAP_API_TOKEN }}
        run: yarn workspace ${{ matrix.workspace }} test
      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: application/${{matrix.workspace}}/cypress/screenshots
      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: application/${{matrix.workspace}}/cypress/videos

  cypress-report:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Merge Mochawesome JSON reports
        run: |
          npx mochawesome-merge \
            "application/*/cypress/reports/*.json" > merged-report.json

      - name: Generate HTML report
        run: |
          npx marge merged-report.json -f merged-report -o .

      - name: Upload merged Cypress HTML report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-merged-report
          path: merged-report.html
