name: Build checks

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: build and check
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install and Use nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
          nvm use
      - name: Enable Corepack
        run: corepack enable
      - name: Configure Environment
        run: cp ./application/backend/.env.test ./application/backend/.env
      - name: Setup Nodejs and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'yarn'
      - run: yarn install && yarn prisma:generate
      - name: Check Types
        run: yarn type-check
      - name: Format Code
        run: yarn format
      - name: Lint Code
        run: yarn lint

  test:
    needs: build
    name: test (${{ matrix.workspace }})
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        workspace: [backend, admin-client, common, user-client, integrations]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Configure Environment
        run: cp ./application/backend/.env.test ./application/backend/.env
      - name: Setup Nodejs and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'yarn'
      - run: yarn install
      - name: Run Tests
        env:
          MAILER_USERNAME: ${{ secrets.TEST_MAILER_USERNAME }}
          MAILER_PASSWORD: ${{ secrets.TEST_MAILER_PASSWORD }}
          CYPRESS_REDCAP_API_TOKEN: ${{ secrets.REDCAP_API_TOKEN }}
        run: yarn workspace ${{ matrix.workspace }} test
