name: E2E tests

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: Image tag to pull for E2E tests
        required: true
      registry_url:
        description: Registry URL to pull images from
        required: true
  workflow_call:
    inputs:
      image_tag:
        type: string
        description: Image tag to pull for E2E tests
        required: true
      registry_url:
        type: string
        description: Registry URL to pull images from
        required: true

jobs:
  run-e2e-tests:
    env:
      IMAGE_TAG: ${{ inputs.image_tag }}
      BACKEND_IMAGE_URL: ${{ inputs.registry_url }}/ctrl-backend:${{ inputs.image_tag }}
      USER_CLIENT_IMAGE_URL: ${{ inputs.registry_url }}/ctrl-user-client:${{ inputs.image_tag }}
      ADMIN_CLIENT_IMAGE_URL: ${{ inputs.registry_url }}/ctrl-admin-client:${{ inputs.image_tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/43338454952/locations/global/workloadIdentityPools/ctrl-id-pool/providers/github-provider'
          service_account: 'ctrl-ci-sa@ctrl-358804.iam.gserviceaccount.com'

      - name: Docker auth
        run: gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - name: Enable Corepack
        run: corepack enable

      - name: Configure Environment
        run: cp ./application/backend/.env.dockere2e ./application/backend/.env

      - name: Parse node version
        id: nvm
        uses: ./.github/actions/parse-node-version

      - name: Setup Nodejs and npm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.node_version }}
          cache: 'yarn'

      - run: yarn install

      - name: Pull and Start Services
        run: docker compose -f docker-compose.e2e.yml up -d --wait

      - name: Run E2E Tests
        run: |
          docker ps # DEBUG
          yarn workspace backend prisma:generate
          npx cypress run --project application/common

      - name: Tear Down Services
        if: always()
        run: |
          docker compose -f docker-compose.e2e.yml down

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: application/common/cypress/screenshots

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: application/common/cypress/videos
