name: Build checks

on: [push]

jobs:
  build-checks:
    name: build checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Configure Environment
        run: cp ./application/backend/.env.test ./application/backend/.env
      - name: Setup Nodejs and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'yarn'
      - run: yarn install && yarn build
      - name: Check Types
        run: yarn type-check
      - name: Format Code
        run: yarn format
      - name: Lint Code
        run: yarn lint
      - name: Run Unit Testing
        env:
          MAILER_USERNAME: ${{ secrets.TEST_MAILER_USERNAME }}
          MAILER_PASSWORD: ${{ secrets.TEST_MAILER_PASSWORD }}
        run: yarn test MailerController
      - name: e2e tests
        run: make e2e

  security-checks:
    uses: Garvan-Data-Science-Platform/reusable-ci-actions/.github/workflows/security-audit.yml@main
    with:
      policy-path: .snyk
    secrets: inherit
