on:
  push:
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: docker build -t ctrl-next:latest -f Dockerfile .
      - run: docker run -h=apphostname ctrl-next:latest 'yarn test'
