name: Build checks

on: [push]

jobs:
  build-checks:
    name: build checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Nodejs and npm
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'
      - name: Check Types
        run: yarn type-check
      - name: Format Code
        run: yarn format
      - name: Lint Code
        run: yarn lint
      - name: Run Unit Testing
        run: yarn test
      - name: e2e tests
        run: make e2e

  security-checks:
    uses: Garvan-Data-Science-Platform/reusable-ci-actions/.github/workflows/security-audit.yml@main
    secrets: inherit
