name: Release

on:
  release:

jobs:
  check_name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: read-yaml-file
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_ver
        with:
          config: ${{ github.workspace }}/.helm/Chart.yaml

      - name: Check helm version
        run: test ${{ github.ref_name }} = ${{ steps.read_ver.outputs['version'] }}

  build_push:
    name: build and push ${{ matrix.name }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        name: [backend, user-client, admin-client]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/43338454952/locations/global/workloadIdentityPools/ctrl-next-id-pool/providers/github-provider'
          service_account: 'ctrl-ci-sa@ctrl-358804.iam.gserviceaccount.com'

      - name: 'Docker auth'
        run: gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: application/${{ matrix.name }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            australia-southeast1-docker.pkg.dev/dsp-registry-410602/garvan-public/ctrl-${{ matrix.name }}:${{ steps.read_ver.outputs['version'] }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  package_push_chart:
    name: package and push helm
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: azure/setup-helm@v4.3.0

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/43338454952/locations/global/workloadIdentityPools/ctrl-next-id-pool/providers/github-provider'
          service_account: 'ctrl-ci-sa@ctrl-358804.iam.gserviceaccount.com'

      - name: Package helm
        run: helm package .helm/ctrl

      - name: Push helm
        run: helm push ctrl-${{ steps.read_ver.outputs['version'] }}.tgz oci://australia-southeast1-docker.pkg.dev/dsp-registry-410602/garvan-public
